"""
Tasks related endpoints and logic

Tasks are auto-generated by AI Counsellor or manually created
They track user progress through stages
"""
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from typing import List, Optional

from .database import get_db
from .models import Task, User
from .auth import get_current_user
from .schemas import TaskCreate, TaskUpdate, TaskResponse
from .stage_logic import STAGE_NAMES

router = APIRouter(prefix="/tasks", tags=["Tasks"])


@router.get("", response_model=List[TaskResponse])
def get_all_tasks(
    stage: Optional[str] = None,
    status_filter: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get all tasks for the current user
    
    Optional filters:
    - stage: Filter by stage (e.g., "STAGE_1_PROFILE")
    - status_filter: Filter by status ("pending", "in_progress", "completed")
    """
    query = db.query(Task).filter(Task.user_id == current_user.id)
    
    if stage:
        query = query.filter(Task.stage == stage)
    
    if status_filter:
        query = query.filter(Task.status == status_filter)
    
    tasks = query.order_by(Task.id).all()
    
    return [
        TaskResponse(
            id=task.id,
            title=task.title,
            stage=task.stage,
            stage_name=STAGE_NAMES.get(task.stage, "Unknown"),
            status=task.status
        )
        for task in tasks
    ]


@router.get("/{task_id}", response_model=TaskResponse)
def get_task(
    task_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get a specific task by ID
    """
    task = db.query(Task).filter(
        Task.id == task_id,
        Task.user_id == current_user.id
    ).first()
    
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Task not found"
        )
    
    return TaskResponse(
        id=task.id,
        title=task.title,
        stage=task.stage,
        stage_name=STAGE_NAMES.get(task.stage, "Unknown"),
        status=task.status
    )


@router.post("", response_model=TaskResponse, status_code=status.HTTP_201_CREATED)
def create_task(
    task_data: TaskCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create a new task
    
    Can be created by:
    - AI Counsellor (automated)
    - User (manual)
    """
    # Create new task
    new_task = Task(
        user_id=current_user.id,
        title=task_data.title,
        stage=task_data.stage if task_data.stage else current_user.current_stage,
        status="pending"
    )
    
    db.add(new_task)
    db.commit()
    db.refresh(new_task)
    
    return TaskResponse(
        id=new_task.id,
        title=new_task.title,
        stage=new_task.stage,
        stage_name=STAGE_NAMES.get(new_task.stage, "Unknown"),
        status=new_task.status
    )


@router.patch("/{task_id}", response_model=TaskResponse)
def update_task(
    task_id: int,
    task_update: TaskUpdate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Update a task
    
    Can update:
    - title
    - status (pending -> in_progress -> completed)
    """
    task = db.query(Task).filter(
        Task.id == task_id,
        Task.user_id == current_user.id
    ).first()
    
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Task not found"
        )
    
    # Update fields if provided
    if task_update.title is not None:
        task.title = task_update.title
    
    if task_update.status is not None:
        # Validate status
        valid_statuses = ["pending", "in_progress", "completed"]
        if task_update.status not in valid_statuses:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Invalid status. Must be one of: {', '.join(valid_statuses)}"
            )
        task.status = task_update.status
    
    db.commit()
    db.refresh(task)
    
    return TaskResponse(
        id=task.id,
        title=task.title,
        stage=task.stage,
        stage_name=STAGE_NAMES.get(task.stage, "Unknown"),
        status=task.status
    )


@router.delete("/{task_id}")
def delete_task(
    task_id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Delete a task
    """
    task = db.query(Task).filter(
        Task.id == task_id,
        Task.user_id == current_user.id
    ).first()
    
    if not task:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Task not found"
        )
    
    db.delete(task)
    db.commit()
    
    return {
        "message": "Task deleted successfully",
        "task_id": task_id
    }


@router.post("/bulk", status_code=status.HTTP_201_CREATED)
def create_bulk_tasks(
    tasks_data: List[TaskCreate],
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Create multiple tasks at once
    
    Useful for AI Counsellor to generate multiple tasks in one go
    """
    created_tasks = []
    
    for task_data in tasks_data:
        new_task = Task(
            user_id=current_user.id,
            title=task_data.title,
            stage=task_data.stage if task_data.stage else current_user.current_stage,
            status="pending"
        )
        db.add(new_task)
        created_tasks.append(new_task)
    
    db.commit()
    
    # Refresh all tasks
    for task in created_tasks:
        db.refresh(task)
    
    return {
        "message": f"{len(created_tasks)} tasks created successfully",
        "tasks": [
            TaskResponse(
                id=task.id,
                title=task.title,
                stage=task.stage,
                stage_name=STAGE_NAMES.get(task.stage, "Unknown"),
                status=task.status
            )
            for task in created_tasks
        ]
    }


@router.get("/by-stage/{stage_name}")
def get_tasks_by_stage(
    stage_name: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Get all tasks for a specific stage
    
    Useful for showing stage-specific tasks on dashboard
    """
    tasks = db.query(Task).filter(
        Task.user_id == current_user.id,
        Task.stage == stage_name
    ).all()
    
    return {
        "stage": stage_name,
        "stage_name": STAGE_NAMES.get(stage_name, "Unknown"),
        "tasks": [
            TaskResponse(
                id=task.id,
                title=task.title,
                stage=task.stage,
                stage_name=STAGE_NAMES.get(task.stage, "Unknown"),
                status=task.status
            )
            for task in tasks
        ],
        "total_count": len(tasks),
        "pending_count": sum(1 for t in tasks if t.status == "pending"),
        "in_progress_count": sum(1 for t in tasks if t.status == "in_progress"),
        "completed_count": sum(1 for t in tasks if t.status == "completed")
    }


@router.post("/generate-default")
def generate_default_tasks(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Generate default tasks based on user's current stage
    
    This creates a starter set of tasks for new users
    """
    stage = current_user.current_stage
    
    # Define default tasks for each stage
    default_tasks = {
        "STAGE_1_PROFILE": [
            "Complete your academic profile",
            "Add your exam scores (IELTS/GRE/etc.)",
            "Define your budget range",
        ],
        "STAGE_2_DISCOVERY": [
            "Research universities in your preferred countries",
            "Check university requirements",
            "Shortlist 3-5 universities",
        ],
        "STAGE_3_LOCKING": [
            "Compare shortlisted universities",
            "Review costs and requirements",
            "Lock at least one university to proceed",
        ],
        "STAGE_4_APPLICATION": [
            "Draft Statement of Purpose (SOP)",
            "Prepare recommendation letters",
            "Gather required documents",
            "Check application deadlines",
        ]
    }
    
    tasks_to_create = default_tasks.get(stage, [])
    
    if not tasks_to_create:
        return {
            "message": "No default tasks for current stage",
            "stage": stage
        }
    
    created_tasks = []
    for task_title in tasks_to_create:
        # Check if task already exists
        existing = db.query(Task).filter(
            Task.user_id == current_user.id,
            Task.title == task_title
        ).first()
        
        if not existing:
            new_task = Task(
                user_id=current_user.id,
                title=task_title,
                stage=stage,
                status="pending"
            )
            db.add(new_task)
            created_tasks.append(new_task)
    
    if created_tasks:
        db.commit()
        for task in created_tasks:
            db.refresh(task)
    
    return {
        "message": f"{len(created_tasks)} default tasks created",
        "stage": stage,
        "stage_name": STAGE_NAMES.get(stage, "Unknown"),
        "tasks": [
            TaskResponse(
                id=task.id,
                title=task.title,
                stage=task.stage,
                stage_name=STAGE_NAMES.get(task.stage, "Unknown"),
                status=task.status
            )
            for task in created_tasks
        ]
    }